"""monopay invoice id

Revision ID: bd01facb7481
Revises: ee0a96658a6f
Create Date: 2026-07-19 10:13:51.581737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd01facb7481'
down_revision: Union[str, None] = 'ee0a96658a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monopay_invoice_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriptions_monopay_invoice_id'), ['monopay_invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_monopay_invoice_id'))
        batch_op.drop_column('monopay_invoice_id')

    # ### end Alembic commands ###
