"""saved charts

Revision ID: ee0a96658a6f
Revises: 97e5ec4091bb
Create Date: 2026-07-16 20:38:59.923679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee0a96658a6f'
down_revision: Union[str, None] = '97e5ec4091bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('chart_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charts_user_id'))

    op.drop_table('charts')
    # ### end Alembic commands ###
